pixelmybit/grent

app/controllers/geniuses_controller.rb, app/controllers/lectures_controller.rb, app/views/geniuses/show.html.erb, app/views/lectures/new.html.erb, app/views/shared/_form-lecture.html.erb, config/routes.rb
added lecture.new to genius show controller
added booking functionality to genius show page
added genuis.new(params[:id]) to lecture controller new
=> Form lecture

app/assets/stylesheets/components/_card_full_photo.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
Added card-full-photo component, it's glorious.
=> card-full-photo created

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/javascript/packs/application.js, app/javascript/plugins/flatpickr.js, app/views/geniuses/show.html.erb, app/views/layouts/application.html.erb, app/views/shared/_form-lecture.html.erb, package.json, yarn.lock
I have added the flatpicker JS to have the form-lecture as a datepicker
=> added flatpickr to form-lecture

db/seeds.rb
=> 28 new geniuses added in the seed

app/assets/stylesheets/components/_card_photo_text.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
=> Card component 2 ready

app/views/shared/_navbar.html.erb
=> added sign-up to navbar

app/models/genius.rb, app/models/photo.rb, app/views/geniuses/index.html.erb, db/migrate/20190611142622_create_photos.rb, db/migrate/20190611143504_remove_photo_from_geniuses.rb, db/schema.rb, test/models/photo_test.rb
=> Added Photo Model & IMAGE DB

app/assets/stylesheets/components/_card_banner.scss
Corrected transition on banner
=> Banner corrected, no transition

app/assets/stylesheets/components/_form.scss, app/controllers/geniuses_controller.rb, app/views/geniuses/new.html.erb, app/views/shared/_form-genius.html.erb, app/views/shared/_form-lecture.html.erb
added genius-form and made it work
=> added genius-form and made it work

app/models/genius.rb, app/models/photo.rb, db/migrate/20190612083237_add_photo_column_to_photos.rb, db/schema.rb, db/seeds.rb
Added photos to genius and connected it to the users i  seeds file
=> 3photos per genius

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_list.scss, app/controllers/geniuses_controller.rb, app/models/genius.rb, app/views/geniuses/new.html.erb, app/views/shared/_list-my-geniuses.html.erb
Boom I hae added all of this low and be hold
=> added the my pages with my genius

app/assets/stylesheets/components/_card_photo_text.scss, app/uploaders/photo_uploader.rb, app/views/geniuses/index.html.erb, app/views/geniuses/show.html.erb
Added card fix and carousel kinda fix
=> Cloudinary fixes

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_list.scss, app/controllers/geniuses_controller.rb, app/views/geniuses/new.html.erb, app/views/shared/_list-bookings.html.erb
Added show my bookings on profile page
=> show all bookings

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_body.scss, app/assets/stylesheets/components/_card_product.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/home.html.erb
fixed link style for home page
added color background in home page
=> fixed linkstyle and bgcolor

app/views/shared/_cards.html.erb
Each card has now a link connection
=> fixed index links

app/assets/stylesheets/components/_card_form.scss, app/assets/stylesheets/pages/_home.scss, app/views/geniuses/new.html.erb, app/views/pages/home.html.erb, app/views/shared/_form-genius.html.erb, app/views/shared/_list-bookings.html.erb, app/views/shared/_list-my-geniuses.html.erb
update homepage text style 
set the new cards on my bookings site
=> style-my page

app/assets/stylesheets/components/_cards.scss, app/views/shared/_cards.html.erb
index icon fixed and genius category added
=> index icon fixed and genius category added

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/config/_fonts.scss, app/views/geniuses/index.html.erb
fontawesome icons fixed
added category to cards
=> fixed more stuff

app/controllers/geniuses_controller.rb, app/models/genius.rb
=> sort by IQ

app/assets/stylesheets/components/_cards.scss
=> added to cards css
